package Model.Game.Card;

public enum GameLogType {
    SELECT_CARD,
    DESELECT_CARD,
    NEXT_PHASE,
    ADD_CARD_TO_HAND,
    SUMMON_MONSTER,
    SUMMON_MONSTER_WITH_1TRIBUTE,
    SUMMON_MONSTER_WITH_2TRIBUTES,
    SET_MONSTER,
    CHANGE_MONSTER_MODE,
    FLIP_SUMMON_MONSTER,
    ATTACK,
    DEATH_MONSTER,
    DIRECT_ATTACK,
    ACTIVE_EFFECT_FIELD,
    ACTIVE_EFFECT_SPELL,
    SET_SPELL
}
